Remove Tinc VPN and make minor changes (#8)
* Remove Tinc VPN and make minor changes

* Removed tinc VPN and restored previously deleted configurations

* fix installers path and scripts

diff --git a/bin/ioisetup b/bin/ioisetup
--- a/bin/ioisetup
+++ b/bin/ioisetup
@@ -1,4 +1,6 @@
 #!/bin/bash
+# Disabled: we no longer use tinc VPN
+# TODO: refactor or remove this script entirely
 
 source /opt/ioi/config.sh
 
@@ -10,24 +12,25 @@ CRED=
 
 main()
 {
-	if check_user; then
-		read -d '' -r MSG<<-EOM
-			This system is already configured for: <b>$USERID</b>\n
-			Do you want to reconfigure to another IOI user?
-			EOM
-		zenity "$ZENTITLE" $ZENARG --question \
-			--text "$MSG"
-		if [ $? -eq 1 ]; then
-			read -d '' -r MSG<<-EOM
-				Keeping configuration for: <b>$USERID</b>\n
-				EOM
-			zenity "$ZENTITLE" $ZENARG --info \
-				--text "$MSG"
-			exit 1
-		fi
-
-		logger -p local0.info "IOISETUP: previously configured for $USERID"
-	fi
+	# --- VPN + Zenity user check (disabled) ---
+	# if check_user; then
+	#     read -d '' -r MSG<<-EOM
+	#         This system is already configured for: <b>$USERID</b>\n
+	#         Do you want to reconfigure to another IOI user?
+	#     EOM
+	#     zenity "$ZENTITLE" $ZENARG --question \
+	#         --text "$MSG"
+	#     if [ $? -eq 1 ]; then
+	#         read -d '' -r MSG<<-EOM
+	#             Keeping configuration for: <b>$USERID</b>\n
+	#         EOM
+	#         zenity "$ZENTITLE" $ZENARG --info \
+	#             --text "$MSG"
+	#         exit 1
+	#     fi
+	#     logger -p local0.info "IOISETUP: previously configured for $USERID"
+	# fi
+	# --- VPN + Zenity user check ---
 
 	while true; do
 		do_setup
@@ -39,110 +42,118 @@ main()
 
 do_setup()
 {
+	# --- Zenity form (disabled) ---
+	# CRED=$(zenity "$ZENTITLE" $ZENARG \
+	# 	--forms --text "Enter contestant credentials" \
+	# 	--add-entry=Username: \
+	# 	--add-password=Password:
+	# )
+	#
+	# if [ $? -eq 1 ]; then
+	# 	return 1
+	# fi
+	# --- Zenity form ---
 
-	CRED=$(zenity "$ZENTITLE" $ZENARG \
-		--forms --text "Enter contestant credentials" \
-		--add-entry=Username: \
-		--add-password=Password:
-	)
+	# For testing purposes only, hardcoded credentials
+	CRED="testuser|testpassword"
 
-	if [ $? -eq 1 ]; then
-		return 1
-	fi
+	# --- Zenity progress bar (disabled) ---
+	# do_core_setup | zenity "$ZENTITLE" $ZENARG \
+	# 	--progress \
+	# 	--no-cancel \
+	# 	--auto-close \
+	# 	--percentage=0
+	#
+	# local retval=${PIPESTATUS[0]}
+	# --- Zenity progress bar ---
 
-	do_core_setup | zenity "$ZENTITLE" $ZENARG \
-		--progress \
-		--no-cancel \
-		--auto-close \
-		--percentage=0
+	do_core_setup
+	local retval=$?
 
-	local retval=${PIPESTATUS[0]}
-
-	if [ ${retval} -eq 1 ]; then
-		read -d '' -r MSG<<-EOM
-			IOI user successfully configured.
-			EOM
-		logger -p local0.info "IOISETUP: configured for ${CRED%|*}"
-		zenity "$ZENTITLE" $ZENARG \
-			--info \
-			--text "$MSG"
-	fi
-
-	if [ ${retval} -eq 2 ]; then
-		read -d '' -r MSG<<-EOM
-			Failed to communicate with the IOI 2025 configuration server.\n
-			Please try again. If this persists, please contact the HTC.
-			EOM
-		zenity "$ZENTITLE" $ZENARG \
-			--error \
-			--text "$MSG"
-	fi
-
-	if [ ${retval} -eq 3 ]; then
-		read -d '' -r MSG<<-EOM
-			Your credentials are not correct. Please try again.
-			EOM
-		zenity "$ZENTITLE" $ZENARG \
-			--error \
-			--text "$MSG"
-	fi
-
-	if [ ${retval} -eq 4 ]; then
-		read -d '' -r MSG<<-EOM
-			Internal error occured. Please contact the HTC.
-			EOM
-		zenity "$ZENTITLE" $ZENARG \
-			--error \
-			--text "$MSG"
-	fi
+	# --- Zenity messages (disabled) ---
+	# if [ ${retval} -eq 1 ]; then
+	# 	read -d '' -r MSG<<-EOM
+	# 		IOI user successfully configured.
+	# 	EOM
+	# 	logger -p local0.info "IOISETUP: configured for ${CRED%|*}"
+	# 	zenity "$ZENTITLE" $ZENARG \
+	# 		--info \
+	# 		--text "$MSG"
+	# fi
+	#
+	# if [ ${retval} -eq 2 ]; then
+	# 	read -d '' -r MSG<<-EOM
+	# 		Failed to communicate with the IOI 2023 configuration server.\n
+	# 		Please try again. If this persists, please contact the HTC.
+	# 	EOM
+	# 	zenity "$ZENTITLE" $ZENARG \
+	# 		--error \
+	# 		--text "$MSG"
+	# fi
+	#
+	# if [ ${retval} -eq 3 ]; then
+	# 	read -d '' -r MSG<<-EOM
+	# 		Your credentials are not correct. Please try again.
+	# 	EOM
+	# 	zenity "$ZENTITLE" $ZENARG \
+	# 		--error \
+	# 		--text "$MSG"
+	# fi
+	#
+	# if [ ${retval} -eq 4 ]; then
+	# 	read -d '' -r MSG<<-EOM
+	# 		Internal error occured. Please contact the HTC.
+	# 	EOM
+	# 	zenity "$ZENTITLE" $ZENARG \
+	# 		--error \
+	# 		--text "$MSG"
+	# fi
+	# --- Zenity messages ---
 
 	return ${retval}
 }
 
 do_core_setup()
 {
+	# --- VPN configuration logic (disabled) ---
 
-	# populate root's known_hosts
-	sudo /opt/ioi/bin/ioiconf.sh keyscan
+	# sudo /opt/ioi/bin/ioiconf.sh keyscan
 
-	# TODO trigger not only on VPN setup:
-	#   Trigger during startup instead?
-	# download new ansible pubkey
-	sudo /opt/ioi/bin/ioiconf.sh getpubkey
-	if [ $? -ne 0 ]; then
-		echo "100"
-		return 2  # connection issue
-	fi
+	# sudo /opt/ioi/bin/ioiconf.sh getpubkey
+	# if [ $? -ne 0 ]; then
+	# 	echo "100"
+	# 	return 2  # connection issue
+	# fi
 
 	echo "25"
 
-	curl -m 5 -s -f -o /tmp/vpn.tar.bz2 "https://$POP_SERVER/pop-config/$CRED" > /dev/null 2>&1
-	RC=$?
-	if [ $RC -eq 22  ]; then
-		echo "100"
-		return 3  # wrong password
-	elif [ $RC -ne 0 ]; then
-		echo "100"
-		return 2  # connection issue
-	fi
+	# curl -m 5 -s -f -o /tmp/vpn.tar.bz2 "https://$POP_SERVER/pop-config/$CRED" > /dev/null 2>&1
+	# RC=$?
+	# if [ $RC -eq 22  ]; then
+	# 	echo "100"
+	# 	return 3  # wrong password
+	# elif [ $RC -ne 0 ]; then
+	# 	echo "100"
+	# 	return 2  # connection issue
+	# fi
 
 	echo "50"
 
-	sudo /opt/ioi/bin/ioiconf.sh vpnconfig /tmp/vpn.tar.bz2 $CRED
-	local retval=$?
-	if [ $retval -ne 0 ]; then
-		echo "100"
-		return 4  # internal error
-	fi
+	# sudo /opt/ioi/bin/ioiconf.sh vpnconfig /tmp/vpn.tar.bz2 $CRED
+	# local retval=$?
+	# if [ $retval -ne 0 ]; then
+	# 	echo "100"
+	# 	return 4  # internal error
+	# fi
 
 	echo "75"
 
-	sudo /opt/ioi/bin/ioiconf.sh vpnrestart
+	# sudo /opt/ioi/bin/ioiconf.sh vpnrestart
 
 	echo "100"
 
+	# --- VPN configuration logic ---
 	return 1
-
 }
 
 check_user()
